version: 2.1
jobs: 
  build:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          - BUNDLER_VERSION:  2.1.4
          - RAILS_ENV: 'test'
      - image: circleci/postgres:postgres:9.5.24-postgis-ram
        environment:
          - 
